apiVersion: apps/v1
kind: Deployment
metadata:
    name: alertmanager-status
    annotations:
        sidecar.jaegertracing.io/inject: "true"
spec:
    replicas: 1
    template:
        spec:
            containers:
                - name: alertmanager-status
                  image: alertmanager-status
                  env:
                      - name: DEBUG_ADDRESS
                        value: 0.0.0.0:8081
                      - name: LOG_LEVEL
                        value: info
                      - name: JAEGER_SERVICE_NAME
                        value: alertmanager-status
                      - name: JAEGER_SAMPLER_TYPE
                        value: const
                      - name: JAEGER_SAMPLER_PARAM
                        value: "1"
                  readinessProbe:
                      httpGet:
                          path: /healthz
                          port: debug
                  livenessProbe:
                      httpGet:
                          path: /livez
                          port: debug
                  ports:
                      - name: public
                        containerPort: 8080
                      - name: debug
                        containerPort: 8081
                  resources:
                      requests:
                          cpu: 10m
                          memory: 45Mi
                      limits:
                          cpu: 1
                          memory: 45Mi
