apiVersion: v1
kind: Service
metadata:
    name: alertmanager-status
spec:
    type: ClusterIP
    ports:
        - name: public
          port: 8080
          targetPort: 8080
        - name: debug
          port: 8081
          targetPort: 8081
